- id: e36d70363e714edca940cdd31d3b3ea7
  alias: ElectrischeDekenUit
  trigger:
  - entity_id: switch.esp_01_relay
    for: 00:{{ states.input_number.slider.state | int }}:00
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data: {}
    entity_id: switch.esp_01_relay
    service: homeassistant.turn_off
- id: 90dadca3afd449f1b86bc92904ffa006
  alias: VerwarmingAan
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - after: '7:00'
    before: '21:59'
    condition: time
  action:
  - data:
      entity_id: climate.downstairs
      preset_mode: none
    service: climate.set_preset_mode
  - data:
      entity_id: climate.downstairs
      hvac_mode: heat
    service: climate.set_hvac_mode
  - data:
      entity_id: climate.downstairs
      temperature: 20
    service: climate.set_temperature
  mode: single
- id: 45cb90b5728f4866b783af601e9f497a
  alias: VerwarmingUit
  trigger:
  - entity_id: group.people
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      preset_mode: away
    entity_id: climate.downstairs
    service: climate.set_preset_mode
  - data: {}
    entity_id: scene.naar_bed
    service: scene.turn_on
- id: ee4548b0219c4215b3ce51e7e0442aed
  alias: woonkmrLampenAan
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - data: {}
    entity_id: scene.lezen
    service: scene.turn_on
- id: '1547220645338'
  alias: iPad opladen
  trigger:
  - below: '15'
    entity_id: sensor.ipad_van_fabian_battery_level
    platform: numeric_state
  condition: []
  action:
  - data:
      message: iPad batterij onder 15%, opladen!
    service: notify.mobile_app_fabian_iphone
- id: '1547221368193'
  alias: Wasmachine klaar
  trigger:
  - below: '6'
    entity_id: sensor.sonoff_pow_power_2
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.esp_04_relay
    state: 'on'
  action:
  - data:
      message: Wasmachine is klaar!!
    service: notify.mobile_app_fabian_iphone
  - data:
      entity_id: switch.esp_04_relay
    service: homeassistant.turn_off
  - data:
      message: Wasmachine is klaar!!
    service: notify.mobile_app_pixel_3a
- id: '1549731767373'
  alias: 3d Printer klaar
  trigger:
  - entity_id: sensor.3d_printer_current_state
    from: Printing
    platform: state
    to: Operational
  condition: []
  action:
  - data:
      message: 3d Printer is klaar!!
    service: notify.mobile_app_fabian_iphone
- id: '1550777256941'
  alias: VerwarmingAanKalender
  trigger:
  - platform: template
    value_template: "{% if states.calendar.fabian_tubbing_nl.attributes.description\
      \ | regex_match('SHFT', ignorecase=False) %}\n    {% set work_start = ( [states.calendar.fabian_tubbing_nl.attributes.start_time]\
      \ | min ) %}\n{% endif %}\n{% set work_time = strptime(work_start,\"%Y-%m-%d\
      \ %H:%M:%S\") %} \n{% set heat_time = work_time.replace(hour=work_time.hour-2)\
      \ %} \n{{ strptime(states.sensor.date_time.state, \"%Y-%m-%d, %H:%M\") == heat_time\
      \ }}"
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - data:
      entity_id: automation.verwarmingaan
    service: automation.trigger
  mode: single
- id: '1570564990849'
  alias: Lampen aan thuis komen als donker
  trigger:
  - entity_id: person.fabian
    from: not_home
    platform: state
    to: home
  - entity_id: person.myrthe
    from: not_home
    platform: state
    to: home
  condition:
  - below: '0.30'
    condition: numeric_state
    entity_id: sensor.living_room_brightness
  action:
  - data: {}
    entity_id: scene.lezen
    service: scene.turn_on
- id: '1570565699168'
  alias: Hoog stroomverbruik en niemand thuis
  trigger:
  - above: '300'
    entity_id: sensor.current_power_usage
    for: 00:15:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.people
    state: not_home
  action:
  - data:
      message: 'Waarschuwing: Hoog stroomverbruik!'
    service: notify.mobile_app_fabian_iphone
- id: '1572021344058'
  alias: Tuin lampen aan thuiskomen
  description: ''
  trigger:
  - entity_id: person.fabian
    from: not_home
    platform: state
    to: home
  - entity_id: person.myrthe
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data: {}
    entity_id: switch.schuur_buiten
    service: homeassistant.turn_on
- id: '1572021985170'
  alias: Tuin lamp uit na 10 min
  description: ''
  trigger:
  - entity_id: person.fabian
    for: 00:10:00
    from: not_home
    platform: state
    to: home
  - entity_id: person.myrthe
    for: 00:10:00
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.schuur_buiten
    service: homeassistant.turn_off
- id: '1575108810940'
  alias: Boomlampjes buiten aan
  description: Lampjes in boom buiten 's nachts aan.
  trigger:
  - event: sunset
    offset: 00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.boom_buiten
    service: switch.turn_on
- id: '1575108876947'
  alias: Boomlampje buiten uit
  description: ''
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.boom_buiten
    service: switch.turn_off
- id: '1586110473108'
  alias: Electrische deken uit Fabian
  description: ''
  trigger:
  - entity_id: switch.esp_06_relay
    for: 00:{{ states.input_number.slider2.state | int }}:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: switch.esp_06_relay
    service: switch.turn_off
  mode: single
- id: '1608041878074'
  alias: HA config backup
  description: ''
  trigger:
  - platform: time
    at: '3:00'
  condition: []
  action:
  - service: hassio.snapshot_full
    data: {}
  mode: single
- id: '1610703834825'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.verwarming_hoog
    to: 'true'
    from: 'false'
  condition: []
  action:
  - service: automation.trigger
    data: {}
    entity_id: automation.verwarmingaan
  mode: single
