- id: e36d70363e714edca940cdd31d3b3ea7
  alias: ElectrischeDekenUit
  trigger:
  - entity_id: switch.esp_01_relay
    for: 00:{{ states.input_number.slider.state | int }}:00
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data: {}
    entity_id: switch.esp_01_relay
    service: homeassistant.turn_off
- id: 90dadca3afd449f1b86bc92904ffa006
  alias: VerwarmingAan
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - after: '7:00'
    before: '21:59'
    condition: time
  action:
  - data:
      entity_id: climate.downstairs
      preset_mode: none
    service: climate.set_preset_mode
  - data:
      entity_id: climate.downstairs
      hvac_mode: heat
    service: climate.set_hvac_mode
  - data:
      entity_id: climate.downstairs
      temperature: 19
    service: climate.set_temperature
- alias: VerwarmingUit
  trigger:
    platform: state
    entity_id: group.people
    from: home
    to: not_home
  action:
  - service: climate.set_preset_mode
    data:
      entity_id: climate.downstairs
      preset_mode: away
  - service: homeassistant.turn_off
    data:
      entity_id: group.woonkamer_groep
  id: 45cb90b5728f4866b783af601e9f497a
- alias: woonkmrLampenAan
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.woonkamer_groep
  id: ee4548b0219c4215b3ce51e7e0442aed
- id: '1547220645338'
  alias: iPad opladen
  trigger:
  - below: '15'
    entity_id: sensor.ipad_van_fabian_battery_level
    platform: numeric_state
  condition: []
  action:
  - data:
      message: iPad batterij onder 15%, opladen!
    service: notify.mobile_app_fabian_iphone
- id: '1547221368193'
  alias: Wasmachine klaar
  trigger:
  - below: '6'
    entity_id: sensor.wasmachine_energie_verbruik
    for: 00:05:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.wasmachine
    state: 'on'
  action:
  - data:
      message: Wasmachine is klaar!!
    service: notify.mobile_app_fabian_iphone
  - data:
      entity_id: switch.wasmachine
    service: homeassistant.turn_off
  - data:
      message: Wasmachine is klaar!!
      target: myrthe_pixel
    service: notify.html5push
- id: '1549731767373'
  alias: 3d Printer klaar
  trigger:
  - entity_id: sensor.3d_printer_current_state
    from: Printing
    platform: state
    to: Operational
  condition: []
  action:
  - data:
      message: 3d Printer is klaar!!
    service: notify.mobile_app_fabian_iphone
- id: '1550777256941'
  alias: VerwarmingAanKalender
  trigger:
  - platform: template
    value_template: '{% set work_start = ( [states.calendar.werk_rooster_fabian.attributes.start_time,states.calendar.werk_rooster_myrthe.attributes.start_time]
      | min ) %} {% set work_time = strptime(work_start,"%Y-%m-%d %H:%M:%S") %} {%
      set heat_time = work_time.replace(hour=work_time.hour-2) %} {{ strptime(states.sensor.date_time.state,
      "%Y-%m-%d, %H:%M") == heat_time }}'
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - data:
      entity_id: automation.verwarmingaan
    service: automation.trigger
- id: '1570564990849'
  alias: Lampen aan thuis komen als donker
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
  condition:
  - below: '0.30'
    condition: numeric_state
    entity_id: sensor.living_room_brightness
  action:
  - data:
      entity_id: group.woonkamer_groep
    service: homeassistant.turn_on
- id: '1570565699168'
  alias: Hoog stroomverbruik en niemand thuis
  trigger:
  - above: '600'
    entity_id: sensor.current_power_usage
    for: 00:15:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.people
    state: not_home
  action:
  - data:
      message: 'Waarschuwing: Hoog stroomverbruik!'
    service: notify.mobile_app_fabian_iphone
- id: '1572021344058'
  alias: Tuin lampen aan thuiskomen
  description: ''
  trigger:
  - entity_id: device_tracker.fabian_iphone_2
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.unifi_58_cb_52_8a_44_2e_default
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: switch.schuur_buiten
    service: homeassistant.turn_on
- id: '1572021985170'
  alias: Tuin lamp uit na 10 min
  description: ''
  trigger:
  - entity_id: device_tracker.fabian_iphone_2
    for: 00:10:00
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.unifi_58_cb_52_8a_44_2e_default
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.schuur_buiten
    service: homeassistant.turn_off
