homeassistant:
  # Name of the location where Home Assistant is running
  #name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: !secret latitude
  #ongitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #elevation: 48
  # metric for Metric, imperial for Imperial
  #unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  
# Default config
default_config:

# Enables the frontend
frontend:

# Enable System Health
system_health:

# Enable map
map:

# Enables configuration UI
config:

# http config
http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: fabiantubbing.duckdns.org
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  #include_used_components: true

# Discover some devices automatically
discovery:

# iOS  component
ios:
mobile_app:

# Enable Homekit
homekit:

# Nest component
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time

# Recorder settings
recorder:
  purge_keep_days: 16
  exclude:
    entities:
      - sensor.last_boot
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.3d_printer_time_elapsed
      - sensor.3d_printer_time_remaining
      - sensor.3d_printer_job_percentage

# Influxdb for storing state data
#influxdb:
#  port: 8086
# database: homeassistant
# username: homeassistant
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state
#  exclude:
#    entities:
#     - sensor.time
#      - sensor.date
#     - sensor.date_time
#      - light.esp_04_led
#      - sensor.3d_printer_time_elapsed
#      - sensor.3d_printer_time_remaining
#      - sensor.3d_printer_job_percentage
#      
# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Buienradar weather
#weather:
#  - platform: buienradar
#    name: Deventer
#    forecast: True

# Google Assistant for google home mini
google_assistant:
  project_id: !secret google_project_id
  exposed_domains: 
    - light
    - switch
    - group
    - media_player
    - climate

# Google calendar for work schedule
#google:
#  client_id: !secret  calendar_client_id
#  client_secret: !secret  calendar_client_secret
#  track_new_calendar: false

# Octoprint config
octoprint:
  host: 192.168.2.31
  api_key: !secret octoprint_api_key
  name: 3d-Printer
  port: 80
  ssl: false
  bed: true
  number_of_tools: 1
  sensors:
    monitored_conditions:
    - 'Current State'
    - 'Temperatures'
    - 'Job Percentage'
    - 'Time Elapsed'
    - 'Time Remaining'

# Octoprint Camera
camera:
  - platform: mjpeg
    name: Octoprint
    still_image_url: http://192.168.2.120/webcam/?action=snapshot
    mjpeg_url: http://192.168.2.120/webcam/?action=stream

# LG WebOS Tv
webostv:
  host: 192.168.2.167
  name: TV woonkamer
#  turn_on_action:
#  service: wake_on_lan.send_magic_packet
#  data:
#    mac: AA-BB-CC-DD-EE-FF
#    broadcast_address: 11.22.33.44

# Time sliders for automation electrische deken uit
input_number:
  slider:
    name: Electrischedeken Timer
    initial: 30
    min: 5
    max: 59
    step: 5

  slider2:
    name: Electrischedeken Timer2
    initial: 30
    min: 5
    max: 59
    step: 5

input_text:
  teams_status:
    name: Microsoft Teams status
    icon: mdi:microsoft-teams
  teams_activity:
    name: Microsoft Teams activity
    icon: mdi:phone-off


# Temp sensor attic
mqtt:
  sensor:
    - name: "Zolder Temp"
      state_topic: "home/DHTtoMQTT/dht1/temp"
      unit_of_measurement: "°C"
      value_template: '{{ value | round(1) -3.5  }}'

# Humidity sensor attic
    - name: "Zolder Luchtvochtigheid"
      state_topic: "home/DHTtoMQTT/dht1/hum"
      unit_of_measurement: "%"
      value_template: '{{ value | round(0) +10  }}'
      icon: mdi:water-percent

# Power sensor washing machine (Sonof pow)
    - name: "Wasmachine Energie verbruik"
      state_topic: "tele/sonoff4/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      qos: 1
      unit_of_measurement: "W"

# Light sensor livingroom
    - name: "Woonkamer licht sensor"
      state_topic: "tele/multisensorwk/SENSOR"
      value_template: '{{ value_json.ANALOG.A0}}'
      qos: 1



# Includes
sensor: !include sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
group: !include groups.yaml
light: !include lights.yaml
scene: !include scenes.yaml