# Sonoff Pow
esphome:
  name: esp_04_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ESPHome_wifi_ssid
  password: !secret ESPHome_wifi_key
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp switch 04"
    password: !secret ESPHome_hotspot

captive_portal:
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret http_password

ota:
  password: !secret http_password

binary_sensor:
  - platform: gpio
    name: "ESP_04_button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relayandled

output:
  - platform: esp8266_pwm
    id: ESP_04_status_led
    pin:
      number: GPIO15
      inverted: False

light:
  - platform: monochromatic
    name: "ESP_04_led"
    output: ESP_04_status_led
    id: led

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: template
    name: "ESP_04_relay"
    optimistic: true
    id: relayandled
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay

sensor:
  - platform: wifi_signal
    name: "ESP_04_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "ESP_04_uptime"
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 2s
    current:
      name: SonOff POW Current
    voltage:
      name: SonOff POW Voltage
    power:
      name: SonOff POW Power
      id: power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led

text_sensor:
  - platform: version
    name: "ESP_04_ESPHome_version"