esphome:
  name: esp_test_01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ESPHome_wifi_ssid
  password: !secret ESPHome_wifi_key

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Test 01 Fallback Hotspot"
    password: "MAoAxCRZbHok"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret http_password

ota:
  password: !secret http_password

web_server:
  port: 80
  
# Test sensor
remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%


remote_receiver:
  pin:
    number: GPIO14
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  