esphome:
  name: esp_powermeter_01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ESPHome_wifi_ssid
  password: !secret ESPHome_wifi_key

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Powermeter 01"
    password: !secret ESPHome_hotspot

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret http_password

ota:
  password: !secret http_password

# Sensor count led pulses, every puls is 1 WH.
binary_sensor:
  - platform: gpio
    id: pulsesensor
    pin: 
      number: GPIO12
      inverted: False
      mode: INPUT
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - output.turn_on: gpio_04
    on_release:
      then:
        - output.turn_off: gpio_04
        - component.update: pulsewidth 

output:
  - platform: gpio
    pin:
      number: GPIO04
    id: gpio_04

sensor:
  - platform: pulse_width
    id: pulsewidth
    pin:
      number: GPIO05
      inverted: True
    unit_of_measurement: 'W'
    name: 'Power Meter'
    accuracy_decimals: 0
    filters:
      - lambda: return (3600/x)  ;
      