esphome:
  name: esp_test_01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ESPHome_wifi_ssid
  password: !secret ESPHome_wifi_key

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret http_password

ota:
  password: !secret http_password

# IR receiver
remote_receiver:
  pin:
    number:  GPIO14
    inverted: yes
  dump: all
