esphome:
  name: esp_test_02
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Tubco"
  password: "test"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Test 02 Fallback Hotspot"
    password: "MAoAxCRZbHok"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Jaap1234"

ota:
  password: "Jaap1234"
