esphome:
  name: lsc_e14_cwww_01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ESPHome_wifi_ssid
  password: !secret ESPHome_wifi_key

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret http_password

ota:
  password: !secret http_password

output:
  - platform: esp8266_pwm
    id: "esp_gpio12"
    frequency: 880 Hz
    pin:
      number: GPIO12
      inverted: False
    min_power: 0.10
    max_power: 0.80

  - platform: esp8266_pwm
    id: "esp_gpio14"
    frequency: 880 Hz
    pin:
      number: GPIO14
      inverted: False
    min_power: 0.10
    max_power: 0.80

light:
  - platform: cwww
    name: "lsc_e14_cwww_01"
    restore_mode: RESTORE_DEFAULT_ON
    cold_white: esp_gpio14
    warm_white: esp_gpio12
    cold_white_color_temperature: 2700 K
    warm_white_color_temperature: 1800 K
    default_transition_length: 2s